[package]
name = "tokentable_v2"
version = "2.5.9"
edition = "2024_07"
authors = ["Jack Xu <jxu@ethsign.xyz>"]
license = "Apache 2.0"
repository = "https://github.com/EthSign/tokentable-v2-starknet"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.8.4"
openzeppelin = "0.17.0"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.31.0" }

[lib]

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"